version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - bodyclose
    - noctx
    - unparam
    - misspell
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
      disable:
        - shadow

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - unparam
          - unused
      - path: "scripts/"
        linters:
          - all

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
