#!/bin/sh
set -e

# Post-release hook: patch the GoReleaser-generated PKGBUILDs with Arch
# options necessary to prevent debug split packages, then push to the
# Arch User Repository (AUR) via the configured SSH key.
#
# We cannot use GoReleaser's built-in AUR push because its PKGBUILD
# template does not support the `options` field (no options= line).
# Instead we set skip_upload=true in .goreleaser.yaml so GoReleaser
# still generates the PKGBUILD/.SRCINFO with correct checksums and
# sources, then this script patches them and handles the push.
#
# Covers both the binary package (kcd-bin, from the `aurs` pipe) and the
# source package (kcd, from the `aur_sources` pipe).
#
# Invoked by .github/workflows/release.yml after goreleaser finishes.

AUR_DIR="${AUR_DIR:-dist/aur}"
AUR_CLONE_BASE="/tmp/kcd-aur-push"
SSH_KEY_DIR="${SSH_KEY_DIR:-$(mktemp -d)}"
SSH_KEY="${SSH_KEY_DIR}/aur_key"

cleanup() {
    rm -rf "${AUR_CLONE_BASE}" "${SSH_KEY_DIR}"
}
trap cleanup EXIT

# ── guard: AUR_KEY must be set by the CI secret ────────────────────────
if [ -z "${AUR_KEY}" ]; then
    echo "aur-push: AUR_KEY not set — skipping AUR push"
    exit 0
fi

# ── set up SSH key for AUR push ────────────────────────────────────────
mkdir -p "${SSH_KEY_DIR}"
echo "${AUR_KEY}" > "${SSH_KEY}"
chmod 600 "${SSH_KEY}"
SSH_CMD="ssh -i ${SSH_KEY} -o StrictHostKeyChecking=accept-new -o IdentitiesOnly=yes"

push_one() {
    name="$1"       # kcd-bin | kcd
    ssh_url="$2"    # AUR remote
    pkgbuild="${AUR_DIR}/${name}.pkgbuild"
    srcinfo="${AUR_DIR}/${name}.srcinfo"
    clone_dir="${AUR_CLONE_BASE}/${name}"

    # ── guard: PKGBUILD must exist (generated by goreleaser) ───────────
    if [ ! -f "${pkgbuild}" ] || [ ! -f "${srcinfo}" ]; then
        echo "aur-push: ${pkgbuild} or ${srcinfo} not found — aborting ${name} (was goreleaser run?)"
        exit 1
    fi

    # ── inject options into PKGBUILD (idempotent) ─────────────────────
    # The options= line prevents Arch's makepkg from creating a -debug split
    # package.  We add it right after the license= line so it sits in the
    # metadata block where makepkg expects it.
    if grep -q '^options=' "${pkgbuild}"; then
        echo "aur-push: options already present in ${name} PKGBUILD"
    else
        sed -i '/^license=/a options=('\''!strip'\'' '\''!debug'\'')' "${pkgbuild}"
        echo "aur-push: injected options into ${name} PKGBUILD"
    fi

    # ── inject options into .SRCINFO (idempotent) ──────────────────────
    if grep -q '^	options = ' "${srcinfo}"; then
        echo "aur-push: options already present in ${name} .SRCINFO"
    else
        sed -i '/^	license = /a\\toptions = !strip !debug' "${srcinfo}"
        echo "aur-push: injected options into ${name} .SRCINFO"
    fi

    # ── clone AUR repo ─────────────────────────────────────────────────
    rm -rf "${clone_dir}"
    git clone -c core.sshCommand="${SSH_CMD}" "${ssh_url}" "${clone_dir}"

    # ── copy patched files ─────────────────────────────────────────────
    cp "${pkgbuild}" "${clone_dir}/PKGBUILD"
    cp "${srcinfo}"  "${clone_dir}/.SRCINFO"

    # ── commit and push ────────────────────────────────────────────────
    cd "${clone_dir}"
    git add PKGBUILD .SRCINFO
    if git diff --cached --quiet; then
        echo "aur-push: no changes to ${name} AUR repo"
    else
        # Derive version from the PKGBUILD itself (avoid tag parsing fragility).
        version=$(grep -oP "^pkgver=\K.+" PKGBUILD | head -1 | sed 's/_/-/g')
        git \
            -c user.name="kcd bot" \
            -c user.email="bot@kcd.invalid" \
            commit -m "Update to v${version}"
        git push
        echo "aur-push: pushed v${version} to ${name} AUR repo"
    fi
    cd - > /dev/null
}

push_one "kcd-bin" "${AUR_SSH_URL:-ssh://aur@aur.archlinux.org/kcd-bin.git}"
push_one "kcd" "${AUR_SSH_URL_SRC:-ssh://aur@aur.archlinux.org/kcd.git}"
