#!/bin/sh
set -e

# Post-release hook: patch the GoReleaser-generated PKGBUILD with Arch
# options necessary to prevent debug split packages, then push to the
# Arch User Repository (AUR) via the configured SSH key.
#
# We cannot use GoReleaser's built-in AUR push because its PKGBUILD
# template does not support the `options` field (no options= line).
# Instead we set skip_upload=true in .goreleaser.yaml so GoReleaser
# still generates the PKGBUILD/.SRCINFO with correct checksums and
# sources, then this script patches them and handles the push.
#
# Invoked by .github/workflows/release.yml after goreleaser finishes.

AUR_DIR="${AUR_DIR:-dist/aur}"
AUR_PKGBUILD="${AUR_DIR}/kcd-bin.pkgbuild"
AUR_SRCINFO="${AUR_DIR}/kcd-bin.srcinfo"
AUR_SSH_URL="${AUR_SSH_URL:-ssh://aur@aur.archlinux.org/kcd-bin.git}"
AUR_CLONE="/tmp/kcd-aur-push"
SSH_KEY_DIR="${SSH_KEY_DIR:-$(mktemp -d)}"
SSH_KEY="${SSH_KEY_DIR}/aur_key"

cleanup() {
    rm -rf "${AUR_CLONE}" "${SSH_KEY_DIR}"
}
trap cleanup EXIT

# ── guard: AUR_KEY must be set by the CI secret ────────────────────────
if [ -z "${AUR_KEY}" ]; then
    echo "aur-push: AUR_KEY not set — skipping AUR push"
    exit 0
fi

# ── guard: PKGBUILD must exist (generated by goreleaser) ───────────────
if [ ! -f "${AUR_PKGBUILD}" ]; then
    echo "aur-push: ${AUR_PKGBUILD} not found — skipping (was goreleaser run?)"
    exit 1
fi

# ── inject options into PKGBUILD (idempotent) ─────────────────────────
# The options= line prevents Arch's makepkg from creating a -debug split
# package.  We add it right after the license= line so it sits in the
# metadata block where makepkg expects it.
if grep -q '^options=' "${AUR_PKGBUILD}"; then
    echo "aur-push: options already present in PKGBUILD"
else
    sed -i '/^license=/a options=('\''!strip'\'' '\''!debug'\'')' "${AUR_PKGBUILD}"
    echo "aur-push: injected options into PKGBUILD"
fi

# ── inject options into .SRCINFO (idempotent) ──────────────────────────
if grep -q '^	options = ' "${AUR_SRCINFO}"; then
    echo "aur-push: options already present in .SRCINFO"
else
    sed -i '/^	license = /a\\toptions = !strip !debug' "${AUR_SRCINFO}"
    echo "aur-push: injected options into .SRCINFO"
fi

# ── set up SSH key for AUR push ────────────────────────────────────────
mkdir -p "${SSH_KEY_DIR}"
echo "${AUR_KEY}" > "${SSH_KEY}"
chmod 600 "${SSH_KEY}"
SSH_CMD="ssh -i ${SSH_KEY} -o StrictHostKeyChecking=accept-new -o IdentitiesOnly=yes"

# ── clone AUR repo ─────────────────────────────────────────────────────
rm -rf "${AUR_CLONE}"
git clone -c core.sshCommand="${SSH_CMD}" "${AUR_SSH_URL}" "${AUR_CLONE}"

# ── copy patched files ─────────────────────────────────────────────────
cp "${AUR_PKGBUILD}" "${AUR_CLONE}/PKGBUILD"
cp "${AUR_SRCINFO}"  "${AUR_CLONE}/.SRCINFO"

# ── commit and push ────────────────────────────────────────────────────
cd "${AUR_CLONE}"
git add PKGBUILD .SRCINFO
if git diff --cached --quiet; then
    echo "aur-push: no changes to AUR repo"
else
    # Derive version from the PKGBUILD itself (avoid tag parsing fragility).
    version=$(grep -oP "^pkgver=\K.+" PKGBUILD | head -1 | sed 's/_/-/g')
    git \
        -c user.name="kcd bot" \
        -c user.email="bot@kcd.invalid" \
        commit -m "Update to v${version}"
    git push
    echo "aur-push: pushed v${version} to AUR"
fi
